- name: Include install_pip
  ansible.builtin.include_tasks:
    file: install_pip.yml

- name: Include install_docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Include install_compose
  ansible.builtin.include_tasks:
    file: install_compose.yml

- name: Include check_docker
  ansible.builtin.include_tasks:
    file: check_docker.yml